# 配置说明详见 local.yml
Configuration:
  status: INFO
  monitorInterval: 600
  name: test_log
  Properties:
    Property:
      - { name: pattern, value: "[时间：%d{HH:mm:ss:SSS}][等级：%-p][线程：%t][类：%l]%m%n" }
      - { name: log_path, value: "/opt/logs" }
      - { name: log_name, value: "test.log" }
  Appenders:
    Console:
      name: console
      target: SYSTEM_OUT
      PatternLayout:
        Pattern: ${pattern}
    RollingFile:
      name: logFile
      fileName: ${log_path}/${log_name}.log
      filePattern: ${log_path}/${log_name}-%d-%i.log
      PatternLayout:
        Pattern: ${pattern}
      Policies:
        TimeBasedTriggeringPolicy:
          interval: 1
        SizeBasedTriggeringPolicy:
          size: 15MB
      DefaultRolloverStrategy:
        fileIndex: "max"
        min: 1
        max: 9999
  Loggers:
    Root:
      additivity: true
      level: info
      includeLocation: true
      AppenderRef:
        - { ref: console, level: info }
        - { ref: logFile, level: info }
    Logger:
      - name: org.apache.kafka
        level: ERROR