server:
  port: 80

spring:
  servlet:
    encoding:
      force: true
  threads:
    virtual:
      enabled: true
  jackson:
    # 设置时区
    time-zone: Asia/Shanghai
#    # 设置时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 设置语言
    locale: CHINESE
    datatype:
      datetime:
        write-dates-as-timestamps: true
        #write-date-timestamps-as-nanoseconds: false